################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "We are a team co-laboring with the Lord in His vineyard by His mercy."
# copyright
copyright = "© 2022 [The New Living Way Blog](#)."


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "We are a team co-laboring with the Lord in His vineyard by His mercy."
# copyright
copyright = "© 2022 [The New Living Way Blog](#)."